site_name: Projeto BOSS - Unity

# Navegação principal
nav:
  - BOSS:
      - Landing Page: "index.md"
      - Checklist Software Livre: "checklist_oss.md"
      - Código de Conduta: "CODE_OF_CONDUCT.md"
      - Contribuindo: "CONTRIBUTING.md"
      - Onboarding: "ONBOARDING.md"
      # - Licença: "LICENSE"
      - Changelog: "CHANGELOG.md"
      - Boas Práticas: "BOAS_PRATICAS.md"
  - Diários de Sofia:
      - Jogo: "jogo/game.md"
      - Conceitos: "projeto/concepts.md"
      - Clean Code: "jogo/clean_code.md"
      - Scripts: "jogo/scripts.md"
      - Backlog: "jogo/backlog.md"
  - Workshops:
      - Tutoriais:
          - Página Home do Workshop: "tutoriais/wokshop_home.md"
          - Configuração do Ambiente (Unity e IDE): "tutoriais/workshop_ambiente.md"
          - Roadmap do Workshop: "tutoriais/workshop_roadmap.md"
          - Criação do primeiro nível: "tutoriais/workshop_primeiro_nivel.md"
          - Movimento do jogador: "tutoriais/workshop_movimento_player.md"
          - Desenvolvimento do nível: "tutoriais/workshop_desenvolvendo_nivel.md"
          - Inimigos e UI: "tutoriais/workshop_inimigos_ui.md"
          - Glossário: "tutoriais/workshop_glossario.md"
          - BRISA: "tutoriais/tutorials.md"
      - Cases:
          - Coral Quest: "tutoriais/coral_quest.md"
      - Dificuldades Subir Ambiente: "projeto/dificuldades_subir_ambiente.md"
  - GCES:
      - Home: "projeto/home.md"
      - Visão de produto e projeto:
          - Visão de produto e projeto: "projeto/product.md"
          - Processos de desenvolvimento de software: "projeto/devprocess.md"
          - Padrões de desenvolvimento: "projeto/patterns.md"
      - Artes e referências: "projeto/references.md"
      - Sprints: "projeto/sprints.md"
      - Roadmaps:
          - Roadmap de desenvolvimento: "projeto/desenvolvimento_roadmap.md"
          - Roadmap de deploy contínuo: "projeto/deploy_continuo_roadmap.md"
          - Roadmap de proposta de contribuição: "projeto/contribuicao_roadmap.md"
      - Releases:
          - Release 1 (22/04/2025): "projeto/releases/release1.md"
          - Release 2 (02/06/2025): "projeto/releases/release2.md"
          - Release 3 (07/07/2025): "projeto/releases/release3.md"

# Configuração do tema Material
theme:
  name: material
  language: pt

  # Recursos de navegação e usabilidade
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  # Paleta de cores e temas
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-6
        name: Usar preferência do sistema
